[tool.semantic_release]
build_command = """

    rm -rf dist/
    rm -rf build/
    rm -rf foo.egg-info/
    python setup.py sdist bdist_wheel

    ./scripts/generate-preview.sh
    git add assets/turbocase-preview.svg
"""


version_variables = ["turbocase/__init__.py:__version__"]
