name: Generic Turbocase Preview Image

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Make Script Executable
        run: chmod +x generate-preview.sh

      - name: Run Script
        run: ./generate-preview.sh
